version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow-server
    ports:
      - "5001:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    restart: unless-stopped

  
